# примеры API-запросов

@baseUrl = http://localhost:8000

# получение объявлений
GET {{baseUrl}}/adv/5/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 39f7b81857414c898535b646b5887ccaf1945364

{
  "title": "new advertisment",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/21/
Content-Type: application/json
Authorization: Token 39f7b81857414c898535b646b5887ccaf1945364

{
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/adv/20/
Authorization: Token 39f7b81857414c898535b646b5887ccaf1945364

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2024-10-01
Content-Type: application/json

###

