# примеры API-запросов

@baseUrl = http://localhost:8000

# получение объявлений
GET {{baseUrl}}/adv/5/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 7a798087fde316fde9fbd3730889cfddd1cda750

{
  "title": "15 Шкафa IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/7/
Content-Type: application/json
Authorization: Token 7a798087fde316fde9fbd3730889cfddd1cda750

{
  "status": "CLOSED"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/adv/5/
Authorization: Token 7a798087fde316fde9fbd3730889cfddd1cda750

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2024-10-01
Content-Type: application/json

###

